### ISSUE TITLE
Error: Please specify --curl-dir=/path/to/built/libcurl 

### ISSUE THREAD

**Issue by taytanqbpass** [Notifysolutions/request_curl#6]
I encountered the error: Please specify --curl-dir=/path/to/built/libcurl while doing a "pip install request_curl".  I have already installed PyCurl using the pycurl-7.45.1-cp311-cp311-win_amd64.whl I have tried all SO links but none of them help. Thanks.

Python Version:  3.11.3
Pycurl version: 7.45.1
OS: Windows 10

**Comment by h3adex** [comment]
Hi,

See this [issue](https://github.com/Notifysolutions/request_curl/issues/5)
